# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dylan Rose
tagline:          'Vision Research & Data'
url:              http://hamcastle1.github.io

paginate:         4

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
