# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dylan Rose
tagline:          'Vision/Data Science'
url:              http://hamcastle1.github.io

paginate:         4

